### PR TITLE
tests: Drop dependency on python-should_be

### PR DESCRIPTION
**Pull request by stanislavlevin**
Migrate should_be assertions to unittest(stdlib) ones.
This requires Python3.2+.

Fixes: https://github.com/pythongssapi/python-gssapi/issues/215

### CODE REVIEW

**Comment by stanislavlevin** [comment]
This morning github experienced availability problems.
That's why I had to push commits without changes (to trigger CI).

**Comment by stanislavlevin** [comment]
Fails are related to MIT krb5 1.18.2:
https://github.com/pythongssapi/python-gssapi/issues/220

**Comment by frozencemetery** [comment]
I think github derped here - I don't remember closing this and the "reopen" option is greyed out.  I'm working on fixing the issue at the moment.

**Comment by stanislavlevin** [comment]
This happened after renaming the branch master -> main.
Anyway, I delay this until https://github.com/pythongssapi/python-gssapi/issues/220 fixed.

**Pull request closed without merging**
