### PR TITLE
Fix Fedora rawhide builders

### PR DESCRIPTION
**Pull request by frozencemetery**
This seems to happen roughly every time it branches; see build log for #124.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
seems reasonable-ish.  Would prefer to have GPG checks, but if they break when fedora branches, I'm not sure there's much we can do about it...

**Comment by frozencemetery** [comment]
Agreed... it's probably not something we want in our release builds if we can avoid it, but on the other hand, release builds aren't working right now and haven't been for a while.

**Comment by frozencemetery** [comment]
@DirectXMan12 Please review added commit.  Thanks!

**Comment by DirectXMan12** [comment]
can you put the RFC number after `is permitted by RFC` (I looked at 2743/2744, but couldn't find exactly what you were referring to), and also put a rough version near `in newever versions` for posterity?  Otherwise, looks good.

**Comment by DirectXMan12** [comment]
(also possibly add a more elaborate comment than `# clockskew`)

**Comment by frozencemetery** [comment]
Added version to commit and clarified language.  Elaborated on comment inline.

**Pull request merged**
