### PR TITLE
Release updates for python-3.8 and removing python2

### PR DESCRIPTION
**Pull request by frozencemetery**
Resolves: #189
Resolves: #181

### CODE REVIEW

**Comment by frozencemetery** [comment]
Windows contributors (@aiudirog @totaam @ofek n'at), the obvious change for removing python2 drops our mingw32 build/release pipeline.  That probably shouldn't go away, right?  What should the Windows matrix look like ideally?

**Comment by frozencemetery** [comment]
Have given up on updating the MacOS builder and opened https://github.com/pythongssapi/python-gssapi/issues/191 for that.

Will merge and tag once we know what the Windows should look like.

**Comment by ofek** [comment]
Thanks!

**Comment by aiudirog** [comment]
I'll look over all of the Windows stuff when I have some time tomorrow evening.

**Comment by aiudirog** [comment]
For removing Python 2.7 on Windows, it looks like the only remaining cleanup is to remove the [extra dependency installation](https://github.com/pythongssapi/python-gssapi/blob/51c83f854c593a52a829ce1a3097c3c9cf4a08bf/.travis/lib-setup.sh#L87). 

On another note, I would personally restore 3.6 wheel deployment on Windows since its EOL isn't until the end of 2021.

We may also want to bump all 3.7 testing and deployment up to 3.7.5 where available, but that's not really a big deal.

**Comment by frozencemetery** [comment]
Thanks for your patience.  I've updated with @aiudirog's suggestions.

**Pull request merged**
