### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by sanglist**
Small fix to enable vas_gssapi
Signed-off-by: Shlomo Anglister  <shlomo.anglister@intel.com>

### CODE REVIEW

**Comment by sanglist** [comment]
Please merge to resolve setup issue

**Comment by simo5** [comment]
@jborean93 this patch looks sane enough, ok if I merge it?

**Comment by jborean93** [comment]
Sorry this one was lost in my sea of notifications. At a glance it seems ok but I do wonder if it might potentially pick up some false positives.

**Comment by jborean93** [comment]
I only want to approve it when I know it won't break other use cases. What setup is causing the problem here, what is the output of `krb5-config --libs gssapi` and is there potentially a better way of fixing your problem.

**Comment by sanglist** [comment]
> I only want to approve it when I know it won't break other use cases. What setup is causing the problem here, what is the output of `krb5-config --libs gssapi` and is there potentially a better way of fixing your problem.

On SLES12 (SuSE 12 Enterprise)

-Wl,-rpath,/opt/quest/lib64:/opt/quest/lib64/support -L/opt/quest/lib64 -lvas -L/opt/quest/lib64/support -lgcc_s -lvas-gssapi -lrt -lresolv

**Comment by jborean93** [comment]
Thanks, is `vas-gssapi` just a SLES thing or is it a specific package here? I'm afraid I'm not familiar with it.

**Comment by sanglist** [comment]
It depends on corporate, right ?
bridging all kinds of authentication protocols originating from a vast application space to corporate authentication.

**Comment by jborean93** [comment]
What I’m trying to get at is how can I test out this scenario. If I need to maintain this I need to know who could be affected and what scenarios this code needs to handle. Do you have any info on this vas-gssapi library. Is it a product I can install or is it a paid product. Are there docs online about it that you can share.

**Comment by sanglist** [comment]
The solution at: [pykrb5/setup.py](https://github.com/jborean93/pykrb5/blob/main/setup.py)
Seems to provide a one size fits all using environment variables.

**Pull request closed without merging**
