### PR TITLE
Add python_requires since upstream still supports 3.5

### PR DESCRIPTION
**Pull request by frozencemetery**
Resolves: #198

@jborean93 PTAL

### CODE REVIEW

**Comment by jborean93** [comment]
Just wanted to check that when you build the package the setuptools version is at `>=24.2.0` as that is what is required for the metadata to be read and generated properly https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires.

Also you state that upstream still supports 3.5 but you've used an fstring with https://github.com/pythongssapi/python-gssapi/commit/5e91aa07271af305b78c9ac45d741f83035ea459#diff-d7c47bf8b55e340087c202452e7c7a8eR64 which is a Python 3.6 only change. The setup.py contents state 3.6+ as well so I'm just a bit confused by the title here.

**Comment by frozencemetery** [comment]
Ah, good question.  "Upstream" there referred to "upstream python".  I'll fix the commit message.

**Comment by frozencemetery** [comment]
To your other question: we build and upload the packages from fedora:latest (currently 31) so we should be good there, and the Windows builds are done from pip.

**Comment by jborean93** [comment]
Awesome thanks for the clarification here and the quick turnaround. Much appreciated.

**Pull request merged**
