### PR TITLE
Docs Revamp

### LINKED ISSUE #34: Improve Docs
The current documentation is a little sparse in terms of things like introductions and examples.  It should have these.  Also, a bit of styling work couldn't hurt either (e.g. on the arguments tables).

### PR DESCRIPTION
**Pull request by DirectXMan12**
This PR contains a large overhaul of the docs.   The general structure of the docs were changed, as well as the style.  Additionally, multiple corrections and improvements were made to the docs.

Closes #34

### CODE REVIEW

**Comment by DirectXMan12** [comment]
see a preview at https://fedorapeople.org/~sross/python-gssapi/docs-preview/

**Comment by frozencemetery** [comment]
In general, this seems good.  I've got some comments inline though.

Additionally, it's kind of annoying that we need to put the method declaration in the documentation **right beneath** the method declaration in the code.  It feels rather redundant.

**Comment by DirectXMan12** [comment]
> Additionally, it's kind of annoying that we need to put the method declaration in the documentation **right beneath** the method declaration in the code.  It feels rather redundant.

This is because those are actually getting translated into C, and C methods don't have any signature information attached.  Therefore, C methods often have a signature line as the first line of their docstring.

**Comment by DirectXMan12** [comment]
WRT "IOV": I suspect it stands for IO Vector, but I couldn't actually find any documentation that spelled that out.

WRT "OID": We could expand the acronym, but most of the other documentation I've seen just refers to them as OIDs, and doesn't expand the acronym.

**Comment by frozencemetery** [comment]
I see what you're saying.  Looks good once Travis finishes.

**Pull request merged**
